### ISSUE TITLE
Questions about new config

### ISSUE THREAD

**Issue by AndyHoggANU** [AndyHoggANU/anu-tub#1]
We have just started working with a new config. A few outstanding questions remain:
* Should we use a julian calendar, or 365-day?
* Are diagnostics functioning properly?
* Should we think about ML restratification or MEKE?
* Are we convinced that convection is now being handled well?
* Should we do a closer cross-check with OM4 standard params before finalising this?

**Comment by angus-g** [comment]
> Should we use a julian calendar, or 365-day?

As long as it's a repeated year, idealised config, 365-day is probably the easiest for analysis without having to deal explicitly with calendars.

> Are diagnostics functioning properly?

What do you mean by this?

> Should we do a closer cross-check with OM4 standard params before finalising this?

This might be a good idea to make sure we're not missing out on any physics, or using outdated parameters.

**Comment by AndyHoggANU** [comment]
> > Are diagnostics functioning properly?
> 
> What do you mean by this?

I renovated the `diag_table` quite a bit and just want to ensure that worked OK. Will do some diagnostics once it has spun up a little more.

**Comment by AndyHoggANU** [comment]
> > > Are diagnostics functioning properly?
> > 
> > 
> > What do you mean by this?
> 
> I renovated the `diag_table` quite a bit and just want to ensure that worked OK. Will do some diagnostics once it has spun up a little more.

Have now looked through some of the diagnostics and they all look pretty sensible.

**Comment by AndyHoggANU** [comment]
Probably the only outstanding issue on the above list is that I am still on the `Julian` calendar, which is a bit annoying, but I don't want to restart just to address this. Note that this is highlighted in #2 so I will close this for now.
