### ISSUE TITLE
Add an adaptive config for default case

### ISSUE THREAD

**Issue by AndyHoggANU** [AndyHoggANU/anu-tub#7]

**Comment by AndyHoggANU** [comment]
@angus-g  -- do we need the `REGRID_COMPRESSIBILITY_FRACTION` defined for AG?

**Comment by angus-g** [comment]
I don't think so, we only use density gradients in AG. That parameter is somewhat targeted at HYCOM1.

**Comment by AndyHoggANU** [comment]
OK, cool -- thanks.

**Comment by AndyHoggANU** [comment]
This case has now run > 150 years, so will close this issue.
